version: '3.8'

services:
  site-vitrine:
    image: nginx:alpine
    container_name: oysi_static
    restart: always
    ports:
      - "127.0.0.1:8090:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - default
      - oysi-net

  backend:
    build: ./backend
    container_name: oysi_static_backend
    restart: always
    env_file:
      - .env
    expose:
      - "8000"

networks:
  oysi-net:
    external: true
